### ISSUE TITLE
How to hide the ugly line on top of the html viewer

### ISSUE THREAD

**Issue by Bri1003** [erinnmclaughlin/MudBlazor.HtmlEditor#20]
How can i remove this line? it's driving me crazy
![image](https://github.com/user-attachments/assets/a8d91900-fe6d-4273-bc02-e46e5f4512de)

**Comment by erinnmclaughlin** [comment]
hey @Bri1003 - thanks for opening the issue.

I honestly don't remember why I decided to add a top border lol. I think it should be pretty straightforward to make this configurable by adding a `Borderless` property to the [`MudHtmlViewer`](https://github.com/erinnmclaughlin/MudBlazor.HtmlEditor/blob/main/src/Tizzani.MudBlazor.HtmlEditor/MudHtmlViewer.razor), and toggling a CSS class based on that.

I'd be happy to accept a PR for this, or I can look into making the change sometime this week.

In the meantime, you should be able to get around this by using your own markup for the HtmlViewer:

```html
<div class="html-content-wrapper ql-snow">
    <div class="ql-editor" style="border: none">
        @((MarkupString)Html)
    </div>
</div>
```

**Comment by Bri1003** [comment]
Thanks for replying, 
It's not even that bad, and I can see it being a thing for design purposes... it just doesn't fit well with the design I'm working on. I'll follow your advice, and great extension btw!
:)
