### ISSUE TITLE
Paragraph dropdown menu is hidden

### ISSUE THREAD

**Issue by ArturasPran** [erinnmclaughlin/MudBlazor.HtmlEditor#7]
When you click on the paragraph drop down button, the choise  menu is hidden in the overflow
![paveikslas](https://github.com/erinnmclaughlin/MudBlazor.HtmlEditor/assets/83699870/9e5a8a21-f468-4927-88e4-927148cd4252)
@erinnmclaughlin

**Comment by erinnmclaughlin** [comment]
hey @ArturasPran sorry for the delay. this has been resolved in the most recent release!
