### ISSUE TITLE
Quill JS 2 update

### ISSUE THREAD

**Issue by dennisrahmen** [erinnmclaughlin/MudBlazor.HtmlEditor#8]
Could you update this to work with the new Quill JS 2 version?
https://slab.com/blog/announcing-quill-2-0/

I just replaced:
`<script src="https://cdn.quilljs.com/1.3.6/quill.min.js"></script>`

With:
`<script src="https://cdn.jsdelivr.net/npm/quill@2/dist/quill.js"></script>`

The UI seems to work fine but the piping for the properties and binding does not seem to work.

**Comment by erinnmclaughlin** [comment]
hey @dennisrahmen - just published a [v2.0 version](https://www.nuget.org/packages/Tizzani.MudBlazor.HtmlEditor/2.0.0) that should be compatible with the new quill versions. See [migrating from v1.0 to v2.0](https://github.com/erinnmclaughlin/MudBlazor.HtmlEditor/tree/v2.0.0?tab=readme-ov-file#migrating-from-v10-to-v20) for more info!

**Comment by dennisrahmen** [comment]
Hey, thanks for the quick update.
Just checked, working great!
