### ISSUE TITLE
Hide ToolBar Contents and Quill JS Initial Loading Issue 

### ISSUE THREAD

**Issue by Sudheesh-TalentzQ** [erinnmclaughlin/MudBlazor.HtmlEditor#9]
It would be great if you can add an option to hide the Image uploader

**Comment by Sudheesh-TalentzQ** [comment]
There are some errors while loading the HTML Editor 

![Screenshot (22)](https://github.com/erinnmclaughlin/MudBlazor.HtmlEditor/assets/149455287/f86ee66c-95a7-4f31-bdd6-a95cb260ed60)
![Screenshot (23)](https://github.com/erinnmclaughlin/MudBlazor.HtmlEditor/assets/149455287/cf8afb79-e46b-438f-bdd9-93a1cfb61392)

But if i refresh the page error is gone but a Deprecation message is shown

![Screenshot (24)](https://github.com/erinnmclaughlin/MudBlazor.HtmlEditor/assets/149455287/66acad56-bfaf-4435-a67a-932c04efbc4e)

Am i missing something ...... i have both mudblazor and mudExtention if that helps.

**Comment by erinnmclaughlin** [comment]
@Sudheesh-TalentzQ

**Comment by Sudheesh-TalentzQ** [comment]
#### Thank you @erinnmclaughlin  for adding the toolbar options ... 
i have tried the new version but still the java script is not loading correctly 

![Screenshot (25)](https://github.com/erinnmclaughlin/MudBlazor.HtmlEditor/assets/149455287/fb8a8ffe-2849-49f0-b222-40e6c189e22c)

But after refreshing the page it works fine but it shows  :  ***quill Cannot import modules/blotFormatter. Are you sure it was registered?*** 
#### Do i need to use JavaScript interop call ?

**Comment by erinnmclaughlin** [comment]
@Sudheesh-TalentzQ just want to confirm: it sounds like the editor is working now, but it is logging an error message about the blotFormatter -- is that correct? That error message is expected if you didn't include this line in your document body:

```razor
 <script src="_content/Tizzani.MudBlazor.HtmlEditor/quill-blot-formatter.min.js"></script> <!-- for image resize -->
```

If you're not using image uploads at all then you can just ignore this message. The blot formatter is an extension that allows resizing images within the editor.

**Comment by Sudheesh-TalentzQ** [comment]
@erinnmclaughlin  It is still throwing this error  ***Quill is not defined***  
In the initial loading only like the screen shot i shared above but if you refresh the page it will load perfectly.
JavaScript library  is not correctly  loaded in Blazor WebAssembly project

**Comment by Sudheesh-TalentzQ** [comment]
@erinnmclaughlin  Looks like we found the issue. 
For some reason Quill.js file did not load properly ( even though it was delivered through CDN).
Can we have a check inside MudHtmlEditor.razor.js file which checks for a valid Quill object and show a friendly message ?
Or you prefer to do it from our side ?

**Comment by erinnmclaughlin** [comment]
I think the default error message of "Quill is not defined" is appropriate here, since this library is heavily dependent on Quill being installed. I'm not able to reproduce this issue, but it might help to self-host quill rather than directly referencing the CDN from your application.

**Comment by Sudheesh-TalentzQ** [comment]
Thank you , @erinnmclaughlin  I will do that
